name: Docker CI

on:
  push:
    branches:
      - dockerlab2
  pull_request:
    branches:
      - dockerlab2

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/factorial-app:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/factorial-app:${{ github.sha }}

    test:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository_owner }}/factorial-app:${{ github.sha }}

      - name: Run tests inside docker container
        run: docker run --rm --entrypoint "" ghcr.io/${{ github.repository_owner }}/factorial-app:${{ github.sha }} dotnet test /app/FactorialApp.Tests/FactorialApp.Tests.csproj --no-build --verbosity normal

