jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t ghcr.io/m1chn3k/factorial-app:latest .

    - name: Run tests in Docker container
      run: docker run --rm --entrypoint dotnet ghcr.io/m1chn3k/factorial-app:latest test /app/FactorialApp.Tests/FactorialApp.Tests.csproj --no-build --verbosity normal
