name: .NET Build and Test

on:
  push:
    branches:
      - lab2-docker
  pull_request:
    branches:
      - lab2-docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Verify .NET version
      run: dotnet --version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build FactorialApp.sln --configuration Release

    - name: Run tests
      run: dotnet test FactorialApp.Tests/FactorialApp.Tests.csproj --no-build --verbosity normal
